# Generated by Django 3.1.7 on 2021-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='institute/upload/')),
                ('disp', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Teachers', models.CharField(max_length=200)),
                ('Subjects', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=200)),
                ('ListStudent', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
                ('Batchs', models.CharField(max_length=200)),
            ],
        ),
    ]
