# Generated by Django 3.1.7 on 2021-04-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210402_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top5institute',
            name='image',
            field=models.FileField(upload_to='media/institute/'),
        ),
    ]
